name: Build Holo Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Login to GitHub Container Registry
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u alphamercury --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Download SteamOS
      run: ./download.sh

    - name: Build base image
      run: sudo ./build.sh

    - name: Cleanup SteamOS image
      run: rm -rf ./steamos_image ./steamos

    - name: Build Rust toolchain image
      run: |
        cd languages
        docker buildx build --platform=linux/amd64,linux/arm64 -t ghcr.io/alphamercury/holo-toolchain-rust:latest -f ./rust.dockerfile .

    - name: Wait for other runs to complete
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Base image
      run: docker push ghcr.io/alphamercury/holo-base:latest

    - name: Push Rust toolchain image
      run: docker push ghcr.io/alphamercury/holo-toolchain-rust:latest

    - name: Log out of GitHub Container Registry
      run: |
        docker logout ghcr.io
